"""Initial schema

Revision ID: 366f35fdc6b0
Revises: 
Create Date: 2026-06-27 05:51:46.673047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '366f35fdc6b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False, comment='Platform origin, e.g. slack, teams'),
    sa.Column('channel_id', sa.String(length=256), nullable=False, comment='Channel or conversation identifier'),
    sa.Column('message_id', sa.String(length=256), nullable=False, comment='Unique message identifier from the platform'),
    sa.Column('sender_name', sa.String(length=256), nullable=True, comment='Display name of the message sender'),
    sa.Column('content', sa.Text(), nullable=False, comment='Message text content'),
    sa.Column('signal_type', postgresql.ENUM('BLOCKER', 'DECISION', 'RISK', 'GENERAL', name='signal_type'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True, comment='Classification confidence score (0.0–1.0)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_signals_channel_id', 'chat_signals', ['channel_id'], unique=False)
    op.create_index('ix_chat_signals_created_at', 'chat_signals', ['created_at'], unique=False)
    op.create_index('ix_chat_signals_signal_type', 'chat_signals', ['signal_type'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True, comment='Origin platform, e.g. Zoom, Teams, Upload'),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='meeting_status'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True, comment='Path to uploaded audio/video file'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI-generated meeting summary'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meetings_created_at', 'meetings', ['created_at'], unique=False)
    op.create_index('ix_meetings_meeting_date', 'meetings', ['meeting_date'], unique=False)
    op.create_index('ix_meetings_status', 'meetings', ['status'], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, comment='Description of the action item'),
    sa.Column('assignee', sa.String(length=256), nullable=True, comment='Person responsible for this action'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='Deadline — nullable to prevent hallucinated dates'),
    sa.Column('verbatim_quote', sa.Text(), nullable=True, comment='Exact transcript quote supporting this action item'),
    sa.Column('status', postgresql.ENUM('DRAFT', 'APPROVED', 'SYNCED', name='insight_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_items_assignee', 'action_items', ['assignee'], unique=False)
    op.create_index('ix_action_items_meeting_id', 'action_items', ['meeting_id'], unique=False)
    op.create_index('ix_action_items_status', 'action_items', ['status'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, comment='Summary of the decision'),
    sa.Column('rationale', sa.Text(), nullable=True, comment='Reasoning behind the decision'),
    sa.Column('verbatim_quote', sa.Text(), nullable=True, comment='Exact transcript quote supporting this decision'),
    sa.Column('status', postgresql.ENUM('DRAFT', 'APPROVED', 'SYNCED', name='insight_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_meeting_id', 'decisions', ['meeting_id'], unique=False)
    op.create_index('ix_decisions_status', 'decisions', ['status'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, comment='Description of the identified risk'),
    sa.Column('severity', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_severity'), nullable=False),
    sa.Column('verbatim_quote', sa.Text(), nullable=True, comment='Exact transcript quote supporting this risk'),
    sa.Column('mitigation', sa.Text(), nullable=True, comment='Suggested mitigation strategy'),
    sa.Column('status', postgresql.ENUM('DRAFT', 'APPROVED', 'SYNCED', name='insight_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risks_meeting_id', 'risks', ['meeting_id'], unique=False)
    op.create_index('ix_risks_severity', 'risks', ['severity'], unique=False)
    op.create_index('ix_risks_status', 'risks', ['status'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False, comment='Order of this segment within the transcript'),
    sa.Column('speaker', sa.String(length=256), nullable=True, comment='Identified speaker name or label'),
    sa.Column('content', sa.Text(), nullable=False, comment='Transcribed text content'),
    sa.Column('start_time', sa.Float(), nullable=True, comment='Segment start time in seconds'),
    sa.Column('end_time', sa.Float(), nullable=True, comment='Segment end time in seconds'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcripts_meeting_id', 'transcripts', ['meeting_id'], unique=False)
    op.create_index('ix_transcripts_segment_index', 'transcripts', ['meeting_id', 'segment_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transcripts_segment_index', table_name='transcripts')
    op.drop_index('ix_transcripts_meeting_id', table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index('ix_risks_status', table_name='risks')
    op.drop_index('ix_risks_severity', table_name='risks')
    op.drop_index('ix_risks_meeting_id', table_name='risks')
    op.drop_table('risks')
    op.drop_index('ix_decisions_status', table_name='decisions')
    op.drop_index('ix_decisions_meeting_id', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_action_items_status', table_name='action_items')
    op.drop_index('ix_action_items_meeting_id', table_name='action_items')
    op.drop_index('ix_action_items_assignee', table_name='action_items')
    op.drop_table('action_items')
    op.drop_index('ix_meetings_status', table_name='meetings')
    op.drop_index('ix_meetings_meeting_date', table_name='meetings')
    op.drop_index('ix_meetings_created_at', table_name='meetings')
    op.drop_table('meetings')
    op.drop_index('ix_chat_signals_signal_type', table_name='chat_signals')
    op.drop_index('ix_chat_signals_created_at', table_name='chat_signals')
    op.drop_index('ix_chat_signals_channel_id', table_name='chat_signals')
    op.drop_table('chat_signals')
    # ### end Alembic commands ###
