"""add_embeddings_to_meetings_and_transcripts

Revision ID: 3714d8d5d642
Revises: a1b2c3d4e5f6
Create Date: 2026-07-01 18:21:15.447756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '3714d8d5d642'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('meetings', sa.Column('summary_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True, comment='AI-generated meeting summary embedding vector'))
    op.add_column('transcripts', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True, comment='Transcript segment content embedding vector'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'embedding')
    op.drop_column('meetings', 'summary_embedding')
    # ### end Alembic commands ###
